export { productController } from "./api-products-controlers.js";
export { postController } from "./api-post-controlers.js";
export { commentController } from "./api-comment-controllers.js";
export { authController } from "./api-auth-controlers.js";
export { dialogController } from "./api-dialog-controllers.js";
export { playerController } from "./api-player-controllers.js";
export { mineGameConroller } from "./api-minecontrollers.js";
export { inventoryGameConroller } from "./api-inventory-controlers.js";
export { adventureGameConroller } from "./api-adventure-controlers.js";
